### ISSUE TITLE
Promcat is not support AWS NLB ?

### ISSUE THREAD

**Issue by 4220182** [sysdiglabs/promcat-resources#144]
Hi Team ,
I can find the resources : AWS ALB, AWS ELB, but not find the AWS NLB resource.

**Comment by daviddetorres** [comment]
Hi! Thanks for the heads up! 

Currently, NLB is not in the roadmap for integrations. However, if you want, you can make it yourself, you can start with any existing AWS integration and modify the exporter configuration ConfigMap to include the `type: nlb` and the metrics from here: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html

It would look like: 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-nlb-config
  namespace: yace
data:
  config.yml: |
    discovery:
      jobs:
      - regions: 
        - us-east-1
        type: nlb
        enableMetricData: true
        metrics: 
          - name: ActiveFlowCount
            statistics:
            - Average
            period: 300
            length: 3600
...
```
